pool:
  vmImage: "ubuntu-latest" # Exécuter sur une VM Ubuntu

trigger:
  - tpfinal # Exécuter le pipeline sur chaque push sur master

variables:
  frontImageNameAndTag: "$(baseImageName)-front:$(env)"

jobs:
  - job: Front
    condition: eq(variables.env, 'dev')
    variables:
      - group: "tp-final-groups"
    steps:
      - template: ./front/_azure-pipelines-build.yml
      - template: ./_docker-build-and-push.yml
        parameters:
          dockerfilePath: $(frontProjectPath)/Dockerfile
          dockerContext: $(frontProjectPath)
          imageName: $(frontImageNameAndTag)
