trigger: none

pool:
  vmImage: "ubuntu-latest" # Exécuter sur une VM Ubuntu

jobs:
  - job: Front
    variables:
      - group: "cours-framework-dev"
    steps:
      - template: ./front/_azure-pipelines-build.yml
